In [2]:
#https://github.com/snorkel-team/snorkel-tutorials/blob/master/spam/01_spam_tutorial.ipynb

In [3]:
%matplotlib inline

import os

# Make sure we're running from the spam/ directory
if os.path.basename(os.getcwd()) == "snorkel-tutorials":
    os.chdir("spam")

# Turn off TensorFlow logging messages
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

# For reproducibility
os.environ["PYTHONHASHSEED"] = "0"

In [4]:
import pandas as pd


DISPLAY_ALL_TEXT = False

pd.set_option("display.max_colwidth", 0 if DISPLAY_ALL_TEXT else 50)

In [5]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import tensorflow as tf
from sklearn.model_selection import train_test_split
import glob
from snorkel.classification.data import DictDataset, DictDataLoader


def load_spam_dataset(load_train_labels: bool = False, split_dev: bool = True):
    
    filenames = sorted(glob.glob("data/Youtube*.csv"))

    dfs = []
    for i, filename in enumerate(filenames, start=1):
        df = pd.read_csv(filename)
        # Lowercase column names
        df.columns = map(str.lower, df.columns)
        # Remove comment_id field
        df = df.drop("comment_id", axis=1)
        # Add field indicating source video
        df["video"] = [i] * len(df)
        # Rename fields
        df = df.rename(columns={"class": "label", "content": "text"})
        # Shuffle order
        df = df.sample(frac=1, random_state=123).reset_index(drop=True)
        dfs.append(df)

    df_train = pd.concat(dfs[:4])

    if split_dev:
        df_dev = df_train.sample(100, random_state=123)

    if not load_train_labels:
        df_train["label"] = np.ones(len(df_train["label"])) * -1
    df_valid_test = dfs[4]
    df_valid, df_test = train_test_split(
        df_valid_test, test_size=250, random_state=123, stratify=df_valid_test.label
    )

    if split_dev:
        return df_train, df_dev, df_valid, df_test
    else:
        return df_train, df_valid, df_test




In [6]:


df_train, df_dev, df_valid, df_test = load_spam_dataset()

# We pull out the label vectors for ease of use later
Y_dev = df_dev.label.values
Y_valid = df_valid.label.values
Y_test = df_test.label.values

In [7]:
df_train

author                        date  \
0                        Alessandro leite         2014-11-05T22:21:36   
1                            Salim Tayara         2014-11-02T14:33:30   
2                                 Phuc Ly         2014-01-20T15:27:47   
3                            DropShotSk8r         2014-01-19T04:27:18   
4                                  css403         2014-11-07T14:25:48   
5                            Giang Nguyen         2014-11-06T04:55:41   
6                            Caius Ballad         2014-11-13T00:58:20   
7                                   Holly         2014-11-06T13:41:30   
8                               King uzzy         2014-11-07T23:19:08   
9                                iKap Taz         2014-11-08T13:34:27   
10                            John Plaatt         2014-11-07T22:22:29   
11                          Praise Samuel         2014-11-08T11:10:30   
12                          Malin Linford         2014-11-05T01:13:43   
13                            Lone Twistt         2013-11-28T17:34:55   
14                              Олег Пась         2014-11-03T23:29:00   
15                                JD COKE         2014-11-08T02:24:02   
16                           zhichao wang         2013-11-29T02:13:56   
17                           Rancy Gaming         2014-11-06T09:41:07   
18               Bishwaroop Bhattacharjee         2014-11-08T12:34:11   
19                              Tedi Foto         2014-11-08T09:33:30   
20                                Tee Tee         2014-11-07T20:16:51   
21                            BeBe Burkey         2013-11-28T16:30:13   
22                           diego acosta         2014-11-08T10:05:27   
23                       Arianna Leighton         2014-11-03T23:02:47   
24                     O sábio das 7 eras         2014-11-07T17:06:48   
25                         witsnow roxiie         2014-11-07T20:45:32   
26                         xxxTheMikeTxxx         2014-11-07T19:33:03   
27                                PacKmaN         2014-11-06T18:23:21   
28                            Ruddy Tapia         2014-01-20T17:58:46   
29                                    전광용         2014-11-07T15:14:48   
..                                    ...                         ...   
418                         Amie Rutledge                         NaN   
419                           Amir bassem                         NaN   
420                     themagicmangotree                         NaN   
421                           Yuliya Meow                         NaN   
422                      David Bottenberg                         NaN   
423                         Jorge Salazar  2015-05-19T18:13:35.054000   
424                                FreshX                         NaN   
425                           Lizzy Molly                         NaN   
426                          scott boshaw  2015-05-21T19:57:17.180000   
427                            Harl Bever  2015-05-19T23:23:30.286000   
428                          Adela Korman                         NaN   
429                        OriginalFreshB                         NaN   
430                         Dragon Addict  2015-05-28T17:49:36.288000   
431                          Wild 'N' Out                         NaN   
432                            Romulus IV  2015-05-28T16:09:13.677000   
433                           Chris Edgar  2015-05-26T18:40:11.037000   
434                              DrAxel81  2015-05-26T23:58:40.132000   
435                              ankan412  2015-05-27T17:38:49.616000   
436                     Victoriaa Hemming  2015-05-24T06:20:53.534000   
437                          Æle Skittles                         NaN   
438                            Karen Cook                         NaN   
439                         Andrew Guasch                         NaN   
440                        leslie mendoza  2015-05-27T04:28:42.896000   
441                 

In [8]:
df_dev.sample(5, random_state=3)

author                        date  \
128  Pepe The Meme King  2015-05-19T03:49:29.427000   
151      Melissa Erhart                         NaN   
31                Angel         2014-11-02T17:27:09   
29        Sandeep Singh  2015-05-23T17:51:58.957000   
237       BigBird Larry  2015-05-24T09:48:00.835000   

                                                  text  label  video  
128                         everyday I&#39;m shufflin      0      3  
151  Check out this playlist on YouTube:chcfcvzfzfb...      1      4  
31   Hi there~I'm group leader of Angel, a rookie K...      1      1  
29                                  Charlie from LOST      0      4  
237  Every single one of his songs brings me back t...      0      4

In [9]:
# For clarity, we define constants to represent the class labels for spam, ham, and abstaining.
ABSTAIN = -1
HAM = 0
SPAM = 1

print(f"Dev SPAM frequency: {100 * (df_dev.label.values == SPAM).mean():.1f}%")

Dev SPAM frequency: 54.0%


In [10]:

df_train[["author", "text", "video"]].sample(20, random_state=2)

author  \
4           ambareesh nimkar   
87              pratik patel   
14                RaMpAgE420   
80              Jason Haddad   
104             austin green   
305                    M.E.S   
22              John Monster   
338          Alanoud Alsaleh   
336        Leonardo Baptista   
143          UKz DoleSnacher   
163            Monica Parker   
129           b0b1t.48058475   
277  MeSoHornyMeLuvULongTime   
265          HarveyIsTheBoss   
214              janez novak   
76              Bizzle Sperq   
123     Gaming and Stuff PRO   
268           Young IncoVEVO   
433              Chris Edgar   
40              rap classics   

                                                  text  video  
4    "eye of the tiger" "i am the champion" seems l...      2  
87                mindblowing dance.,.,.superbbb song      3  
14          Check out Berzerk video on my channel ! :D      4  
80   Hey, check out my new website!! This site is a...      1  
104                   Eminem is my insperasen and fav      4  
305  hey guys look im aware im spamming and it piss...      4  
22   Οh my god ... Roar is the most liked video at ...      2  
338  I started hating Katy Perry after finding out ...      2  
336  http://www.avaaz.org/po/petition/Youtube_Corpo...      1  
143                        Remove This video its wank      1  
163                  Check out this video on YouTube:      3  
129  i rekt ur mum last nite. cuz da haterz were 2 ...      2  
277  This video is so racist!!! There are only anim...      2  
265  You gotta say its funny. well not 2 billion wo...      1  
214  share and like this page to win a hand signed ...      4  
76   https://www.facebook.com/nicushorbboy add mee ...      1  
123  Hello! Do you like gaming, art videos, scienti...      1  
268  Check out my Music Videos! and PLEASE SUBSCRIB...      1  
433                 Love the way you lie - Driveshaft      4  
40      check out my channel for rap and hip hop music      4

In [11]:
from snorkel.labeling import labeling_function


@labeling_function()
def check(x):
    return SPAM if "check" in x.text.lower() else ABSTAIN


@labeling_function()
def check_out(x):
    return SPAM if "check out" in x.text.lower() else ABSTAIN

In [12]:
df_train.head()

author                 date  \
0  Alessandro leite  2014-11-05T22:21:36   
1      Salim Tayara  2014-11-02T14:33:30   
2           Phuc Ly  2014-01-20T15:27:47   
3      DropShotSk8r  2014-01-19T04:27:18   
4            css403  2014-11-07T14:25:48   

                                                text  label  video  
0  pls http://www10.vakinha.com.br/VaquinhaE.aspx...   -1.0      1  
1  if your like drones, plz subscribe to Kamal Ta...   -1.0      1  
2                     go here to check the views :3   -1.0      1  
3            Came here to check the views, goodbye.   -1.0      1  
4                      i am 2,126,492,636 viewer :D   -1.0      1

In [13]:
from snorkel.labeling import PandasLFApplier

lfs = [check_out, check]


In [14]:

applier = PandasLFApplier(lfs=lfs)


In [15]:
import pandas
print(pandas.__version__)

0.24.0


In [16]:
L_train = applier.apply(df=df_train)
L_dev = applier.apply(df=df_dev)

100%|██████████| 100/100 [00:00<00:00, 14777.52it/s]


In [17]:
L_train

array([[-1, -1],
       [-1, -1],
       [-1,  1],
       ...,
       [ 1,  1],
       [-1,  1],
       [ 1,  1]])

In [18]:
from snorkel.labeling.apply.dask import PandasParallelLFApplier

In [19]:
applier_pll = PandasParallelLFApplier(lfs=lfs)

In [20]:
L_train2 = applier_pll.apply(df_train, n_parallel=8)

In [35]:
L_train.shape, L_train2.shape

((1586, 2), (1586, 2))

In [36]:
np.array_equal(L_train, L_train2)

False

In [33]:
np.equal(L_train, L_train2)

array([[ True,  True],
       [ True,  True],
       [ True, False],
       ...,
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [34]:
L_train[3], L_train2[3]

(array([-1,  1]), array([1, 1]))

In [22]:
coverage_check_out, coverage_check = (L_train != ABSTAIN).mean(axis=0)
print(f"check_out coverage: {coverage_check_out * 100:.1f}%")
print(f"check coverage: {coverage_check * 100:.1f}%")

check_out coverage: 21.4%
check coverage: 25.8%


In [24]:
from snorkel.labeling import LFAnalysis

LFAnalysis(L=L_train, lfs=lfs).lf_summary()

j Polarity  Coverage  Overlaps  Conflicts
check_out  0      [1]  0.214376  0.214376        0.0
check      1      [1]  0.257881  0.214376        0.0

In [25]:
LFAnalysis(L=L_train2, lfs=lfs).lf_summary()

j Polarity  Coverage  Overlaps  Conflicts
check_out  0      [1]  0.214376  0.214376        0.0
check      1      [1]  0.257881  0.214376        0.0